version: '3.8'

services:
  maf-mongo:
    image: mongo:latest
    container_name: maf-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - maf-net

volumes:
  mongo_data:

networks:
  maf-net:
    driver: bridge
