version: '3.8'

services:
  maf-redis:
    image: redis:alpine
    container_name: maf-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - maf-net

  maf-mongo:
    image: mongo:latest
    container_name: maf-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - maf-net

volumes:
  redis_data:
  mongo_data:

networks:
  maf-net:
    driver: bridge
